/**
 * Guessing Game
 * Maxwell Phillips
 *  29 September 2017
 *  A small game where the player must guess a random number generated by the computer.
 */

import java.util.Scanner;
import java.lang.Math;
public class GuessingGame {

	public static void main(String[] args) {
		//variables
		int userNum;
		int secretNum = (int)((20 - 1 + 1)*Math.random() + 1);
		
		//input
		Scanner input = new Scanner(System.in);
		System.out.print("Enter a number between 1 and 20: ");
		userNum = input.nextInt();
		
		//Output results
		System.out.println("Computer\'s Number: "+secretNum);
		System.out.println("Player\'s Number: "+userNum);
		if (userNum == secretNum) {
			System.out.println("You won!");
		} else {
			System.out.println("Better luck next time.");
		}
		input.close();
	}

}
