/**
 * Guessing Game
 * Maxwell Phillips
 * 5 December 2017
 * A small game where the player must guess a random number generated by the computer.
 */

import java.util.Scanner;
import java.lang.Math;
public class Exercise10 {
	/**
	 * Pre:
	 * @param guess: Int value for the number the player guessed.
	 * @param num: Int value for the actual number the player is trying to guess.
	 * Post: Prints a message to the console indicating whether to guess a larger or smaller number to the player, depending on their last guess.
	 */
	public static void giveHint(int guess, int num) {
		if (guess > num) {
			System.out.println("Hint: try a lower numer.");
		} else if (guess < num) {
			System.out.println("Hint: try a higher numer.");
		}
	}
	public static void main(String[] args) {
		//variables
		int userNum;
		int secretNum = (int)((20 - 1 + 1)*Math.random() + 1);
		
		Scanner input = new Scanner(System.in);
		
		while (true) {
			
			//input
			System.out.print("Enter a number between 1 and 20: ");
			userNum = input.nextInt();
		
			//Output results
			if (userNum == secretNum) {
				System.out.println("You won!");
				break;
			}
			giveHint(userNum, secretNum); //give a hint!
		}
		input.close();
	}

}
